######################################################################
# Automatically generated by qmake (2.01a) Jo iun. 9 19:03:53 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += App.h Controller.h Country.h QTUI.h Repository.h ui_design.h
SOURCES += App.cpp Country.cpp main.cpp
