######################################################################
# Automatically generated by qmake (2.01a) Du mai 29 21:04:21 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += App.h Bill.h Controller.h QtUi.h Repository.h
FORMS += design.ui
SOURCES += App.cpp Bill.cpp Controller.cpp main.cpp Repository.cpp
